/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react'

export const translations = {
  en: {
    nav_analyze: 'ANALYZE', nav_learn: 'LEARN', nav_about: 'ABOUT',
    nav_quiz: 'QUIZ', nav_subtitle: 'CYBER INTELLIGENCE',
    nav_logout: 'LOGOUT', nav_logout_desc: 'Return to onboarding',
    nav_cve: 'VULN LOOKUP', nav_ioc: 'IOC SEARCH',
    nav_explore: 'EXPLORE THREATS',
    ob_init: '▸ SYSTEM INITIALIZATION',
    ob_step1_label: '▸ STEP 01 — LANGUAGE PREFERENCE',
    ob_step1_title: 'What should we call you?',
    ob_step1_desc: 'Your experience will be personalized based on your profile.',
    ob_step1_placeholder: 'Enter your name...',
    ob_step2_label: '▸ STEP 02 — IDENTIFICATION',
    ob_step2_title: 'Welcome', ob_step2_desc: 'Select your background so the AI can tailor explanations specifically for you.',
    ob_step3_label: '▸ STEP 03 — PROFILE CALIBRATION',
    ob_step3_title: 'Choose your language', ob_step3_desc: 'Select the language for your entire experience.',
    ob_continue: 'CONTINUE ▸', ob_initialize: 'INITIALIZE SYSTEM ▸',
    bg_student: 'Student', bg_student_desc: 'Learning about technology and cybersecurity',
    bg_it: 'IT Professional', bg_it_desc: 'Work in IT but not in security specifically',
    bg_manager: 'Manager / Executive', bg_manager_desc: 'Lead teams and need to understand business impact',
    bg_developer: 'Developer', bg_developer_desc: 'Write code and build software products',
    bg_general: 'General Public', bg_general_desc: 'Not from tech — just want to stay informed',
    bg_security: 'Security Analyst', bg_security_desc: 'Work in cybersecurity or SOC environment',
    home_ready: 'SYSTEM READY — PROFILE LOADED', home_welcome: 'Welcome back',
    home_calibrated: 'Calibrated for', home_level: 'level',
    home_label: '▸ THREAT INTELLIGENCE DECODER',
    home_title1: 'ANY CYBER ATTACK.', home_title2: 'PLAIN ENGLISH.',
    home_subtitle: 'Paste a URL or article text. AI explains it in language anyone understands.',
    home_tab_url: 'PASTE URL', home_tab_text: 'PASTE TEXT',
    home_url_label: '▸ ENTER ARTICLE URL',
    home_url_desc: 'Paste any cybersecurity news URL — we fetch and analyze it automatically.',
    home_url_placeholder: 'https://thehackernews.com/...',
    home_url_works: 'Works with: The Hacker News, Bleeping Computer, Krebs on Security, etc.',
    home_fetch_btn: 'FETCH & DECODE ▸', home_fetching: 'FETCHING...',
    home_text_label: '▸ PASTE ARTICLE TEXT',
    home_text_placeholder: 'Paste cybersecurity article text here...',
    home_decode_btn: 'DECODE THREAT ▸', home_chars: 'characters loaded',
    home_awaiting: 'Awaiting input...',
    home_examples: '▸ TRY AN EXAMPLE',
    home_fetch_success: 'Article fetched — loading analysis...',
    home_fetch_tip: 'Tip: Some websites block automated access. Try the Paste Text tab instead.',
    home_feat_url: 'URL OR TEXT', home_feat_url_desc: 'Paste a link or copy article text directly.',
    home_feat_timeline: 'ATTACK TIMELINE', home_feat_timeline_desc: 'Visual step-by-step attack breakdown.',
    home_feat_ioc: 'IOC + CVE + ATT&CK', home_feat_ioc_desc: 'Every technical term explained simply.',
    home_feat_personal: 'PERSONALIZED', home_feat_personal_desc: 'Explanations matched to your background.',
    home_example_wannacry: 'WannaCry Ransomware', home_example_heartbleed: 'Heartbleed Bug', home_example_solarwinds: 'SolarWinds Attack',
    exp_back: 'NEW ANALYSIS', exp_error_title: '▸ SYSTEM ERROR', exp_return: 'RETURN',
    exp_complete: '▸ THREAT ANALYSIS COMPLETE', exp_summary_label: 'SIMPLE SUMMARY',
    exp_overview: '▸ INCIDENT OVERVIEW', exp_attacker: 'ATTACKER', exp_victim: 'VICTIM',
    exp_analogy: '▸ REAL LIFE ANALOGY', exp_timeline: '▸ ATTACK TIMELINE',
    exp_intel: '▸ INTELLIGENCE BREAKDOWN',
    exp_ioc_title: 'IOC — INDICATORS OF COMPROMISE', exp_ioc_what: 'WHAT IS AN IOC?',
    exp_ioc_simple: 'Digital fingerprints left by hackers — like suspicious websites, file names, or IP addresses that prove an attack happened.',
    exp_cve_title: 'CVE — SOFTWARE VULNERABILITY', exp_cve_what: 'WHAT IS A CVE?',
    exp_cve_simple: 'A numbered catalog of known software bugs. CVE-YEAR-NUMBER identifies a specific weakness — like a broken lock on a specific door.',
    exp_attck_title: 'MITRE ATT&CK TECHNIQUES', exp_attck_what: 'WHAT IS MITRE ATT&CK?',
    exp_attck_simple: 'A dictionary of every known hacker move — like a playbook coded as T-numbers. Helps defenders know what to watch for.',
    exp_found: 'FOUND', exp_none: 'NONE FOUND', exp_identified: 'IDENTIFIED', exp_tactics: 'TACTICS',
    exp_jargon: '▸ JARGON DECODER', exp_risk: '▸ WHO IS AT RISK', exp_safe: '▸ HOW TO STAY SAFE',
    exp_quiz_btn: '▸ TEST YOUR UNDERSTANDING', exp_quiz_desc: 'Take a 5-question quiz based on this article',
    exp_stix_btn: '▸ VIEW THREAT INTELLIGENCE BUNDLE', exp_stix_desc: 'See structured threat data explained simply',
    quiz_label: '▸ KNOWLEDGE ASSESSMENT', quiz_title: 'TEST YOUR UNDERSTANDING',
    quiz_generating: 'Generating questions...', quiz_question: 'QUESTION', quiz_of: 'OF',
    quiz_correct: 'CORRECT', quiz_wrong: 'INCORRECT', quiz_explanation: 'EXPLANATION',
    quiz_next: 'NEXT QUESTION ▸', quiz_finish: 'SEE RESULTS ▸', quiz_results: '▸ QUIZ COMPLETE',
    quiz_score: 'YOUR SCORE', quiz_excellent: 'Excellent! You understood this threat well.',
    quiz_good: 'Good job! You grasped most of the key points.',
    quiz_keep: 'Keep learning! Review the analysis again.',
    quiz_retry: 'RETRY QUIZ ▸', quiz_back: 'BACK TO ANALYSIS', quiz_error: 'Could not generate quiz. Please try again.',
    loading_title: 'ANALYZING THREAT', loading_desc: 'AI decoding in progress...',
    learn_label: '▸ KNOWLEDGE BASE', learn_title: 'CYBER DICTIONARY',
    learn_subtitle: 'Confusing cyber words explained like a friend would explain them.',
    learn_analogy: 'Think of it like this', learn_example: 'Real story', learn_format: 'Format',
    learn_cve: 'CVE', learn_cve_full: 'Common Vulnerabilities and Exposures',
    learn_cve_simple: 'Every software has bugs. When a bug is bad enough for hackers to exploit, it gets an official ID number called a CVE — like a police case number for a software crime.',
    learn_cve_analogy: 'Imagine someone discovers that all Model X cars have a faulty door lock. Instead of telling every owner separately, the government registers it officially: Security Issue CVE-2021-44228 — the Model X door lock can be opened with a hairpin.',
    learn_cve_example: 'CVE-2021-44228 (Log4Shell) — A popular Java tool had a bug where sending one special message gave a hacker full server control. Over 3 billion devices were at risk. Companies patched systems for months.',
    learn_cve_format: 'CVE - YEAR - NUMBER',
    learn_ioc: 'IOC', learn_ioc_full: 'Indicators of Compromise',
    learn_ioc_simple: 'After a hacker breaks in, they leave traces — just like a burglar leaves fingerprints. These digital traces are called IOCs. Security teams collect them to know if their systems were touched.',
    learn_ioc_analogy: 'You come home and notice muddy footprints, a broken window latch, and your laptop moved. You did not see the burglar — but the footprints, broken latch, and moved laptop are IOCs — evidence someone was there.',
    learn_ioc_example: 'In the SolarWinds attack, hackers left a file called SUNBURST on infected systems. That filename became an IOC. Security teams worldwide searched their own systems for that exact file to see if they were also hacked.',
    learn_ioc_format: 'IPs, URLs, file hashes, domain names, email addresses',
    learn_mitre: 'MITRE ATT&CK', learn_mitre_full: 'Adversarial Tactics, Techniques & Common Knowledge',
    learn_mitre_simple: 'Hackers are not random. They follow patterns — like thieves who always case a building first. MITRE studied thousands of real attacks and catalogued every pattern with a code like T1566.',
    learn_mitre_analogy: 'A chess grandmaster sees one move and immediately recognizes "the Sicilian Defense" — knowing exactly what comes next. Security experts use ATT&CK the same way. When they see T1566, they know phishing is happening and what to do.',
    learn_mitre_example: 'T1566 = hacker sent fake emails. T1486 = hacker locked all your files. When WannaCry hit hospitals, analysts used ATT&CK codes to understand the attack and warn other hospitals immediately.',
    learn_mitre_format: 'T + 4 digits (e.g. T1566) — sub-techniques add .001',
    learn_ransomware: 'Ransomware', learn_ransomware_full: 'Ransom + Software',
    learn_ransomware_simple: 'A virus that sneaks into your computer, locks all your files so you cannot open them, then demands money. If you pay, they may or may not unlock your files.',
    learn_ransomware_analogy: 'You arrive at work and all filing cabinets are locked with new padlocks you have no keys for. There is a note: Pay 5 lakh rupees in Bitcoin and we will give you the keys. That is ransomware — but for computer files.',
    learn_ransomware_example: 'In 2017, WannaCry attacked the UK National Health Service. Doctors could not access patient records. Surgeries were cancelled. Ambulances diverted. All because one hospital did not install a Windows update.',
    learn_ransomware_format: 'Usually spreads via email attachments or unpatched software',
    learn_phishing: 'Phishing', learn_phishing_full: 'Fishing for your information',
    learn_phishing_simple: 'A fake message designed to trick you into giving your password, clicking a bad link, or entering details into a fake website. It looks real but is a trap.',
    learn_phishing_analogy: 'You get a WhatsApp message from what looks like your bank: Your account is locked — click here to verify. You click, enter details on a page that looks exactly like your bank — and now the hacker has your password. The fake message is the fishing hook. You are the fish.',
    learn_phishing_example: 'In 2020, Twitter was hacked through phishing. A hacker called employees pretending to be IT support, got their login details, then tweeted a Bitcoin scam from Obama and Musk accounts.',
    learn_phishing_format: 'Email, SMS, voice calls (vishing), fake websites',
    learn_zeroday: 'Zero-Day', learn_zeroday_full: 'Zero days to fix it',
    learn_zeroday_simple: 'A bug in software that the company does not know about yet — or just found — so there is no fix available. Hackers who know about it can attack everyone using that software and there is nothing users can do.',
    learn_zeroday_analogy: 'Your apartment front door lock can be opened with a credit card. The landlord does not know this. A thief discovers the trick first. Until the landlord replaces all locks, every apartment is vulnerable. Tenants cannot fix it themselves.',
    learn_zeroday_example: 'In 2010, Stuxnet physically destroyed Iranian nuclear centrifuges using zero-day attacks. The attackers found bugs in Windows and industrial software that no one had ever discovered before. Iran had no idea for months.',
    learn_zeroday_format: 'Called 0day — the most dangerous type of vulnerability',
    about_label: '▸ ABOUT', about_title: 'WHAT IS HACKDECODED?',
    about_problem_title: 'THE PROBLEM WE NOTICED',
    about_problem_desc: 'Cybersecurity news is written for experts. When hospitals get hacked or your data gets stolen, articles say things like "threat actor exploited CVE-2024-1234 via T1566 phishing vector." Most people read that and have no idea what just happened to them.',
    about_solution_title: 'WHAT WE BUILT',
    about_solution_desc: 'HackDecoded is an AI translator. You paste any cybersecurity article and we explain what happened, who did it, how they did it, and what you should do — in your language, at your level.',
    about_who_title: 'WHO IS THIS FOR',
    about_who_desc: 'Anyone who wants to understand cybersecurity without needing a computer science degree. Students, managers, employees, business owners, parents — if you use a phone or computer, cyber threats affect you.',
    about_how_title: 'HOW IT WORKS',
    about_how_desc: 'Tell us your background and language preference. Then paste any threat article. Our AI powered by Llama 3.3 reads it and rewrites everything in language that makes sense to you.',
    about_features_title: 'WHAT YOU CAN DO HERE',
    about_features_desc: 'Decode any threat article into plain language. Look up CVE vulnerability numbers. Explore live threat intelligence. Take a quiz to test understanding. Learn cyber terms explained like a friend would explain them.',
    about_disclaimer_title: 'IMPORTANT NOTE',
    about_disclaimer_desc: 'HackDecoded is for learning and awareness. Our AI explanations should not replace professional security advice. For serious security decisions, always consult qualified professionals.',
    cve_page_label: '▸ VULNERABILITY DATABASE', cve_page_title: 'VULNERABILITY LOOKUP',
    cve_page_subtitle: 'Type any CVE number and we will tell you exactly what the bug is, how dangerous it is, and what it means — in plain English.',
    cve_what_label: '▸ WHAT IS A CVE NUMBER?',
    cve_what_text: 'Think of a CVE like a case number at a police station. Every time someone discovers a software bug dangerous enough for hackers to use, it gets registered officially with a unique number.',
    cve_format_label: '▸ HOW TO READ THE NUMBER',
    cve_input_label: '▸ ENTER CVE NUMBER',
    cve_search_button: 'LOOK UP ▸',
    cve_search_error: 'CVE not found. Please check the format and try again.',
    cve_search_error_title: '▸ NOT FOUND',
    cve_published: 'Published', cve_severity: 'SEVERITY', cve_cvss_score: 'DANGER SCORE',
    cve_description: '▸ WHAT IS THIS BUG?', cve_cvss_vector: '▸ TECHNICAL DETAILS',
    cve_vector_explain_label: '▸ WHAT DOES THIS MEAN IN SIMPLE WORDS?',
    cve_references: '▸ OFFICIAL SOURCES',
    cve_tip: 'WHAT SHOULD YOU DO?',
    cve_tip_text: 'The danger score goes from 0 to 10. Score 9-10 (Critical) = building is on fire, act now. Score 7-8.9 (High) = smoke detected, act urgently. Score 4-6.9 (Medium) = check and fix soon. Score 0-3.9 (Low) = minor issue, fix when convenient.',
    cve_try_example: '▸ TRY AN EXAMPLE', cve_ai_label: '▸ SIMPLE EXPLANATION', cve_ai_loading: 'AI is reading the technical details...',
    ioc_page_label: '▸ IOC INTELLIGENCE', ioc_page_title: 'IOC SEARCH',
    ioc_page_subtitle: 'Search any suspicious IP, URL, domain, or file hash to see if it has been flagged by the security community.',
    ioc_what_label: '▸ WHAT IS AN IOC?',
    ioc_what_text: 'IOC stands for Indicator of Compromise — think of it as a wanted poster for digital criminals. If security researchers have seen it in an attack, it becomes an IOC.',
    ioc_input_label: '▸ ENTER SUSPICIOUS INDICATOR',
    ioc_placeholder: 'Enter IP address, URL, domain, or file hash...',
    ioc_search_button: 'CHECK ▸', ioc_found: 'FLAGGED AS MALICIOUS',
    ioc_not_found: 'NOT IN OUR DATABASE',
    ioc_not_found_desc: 'This indicator has not been flagged in our database. This does not guarantee it is safe — always exercise caution.',
    ioc_type: 'TYPE', ioc_risk: 'RISK LEVEL', ioc_context: 'CONTEXT', ioc_action: 'RECOMMENDED ACTION',
    explore_label: '▸ LIVE THREAT INTELLIGENCE', explore_title: 'EXPLORE THREATS',
    explore_subtitle: 'Latest cyber threats explained in plain language. Updated from real security news.',
    explore_new_badge: 'NEW THREAT', explore_learn_more: 'READ FULL ANALYSIS ▸',
    explore_loading: 'Fetching latest threats...',
    explore_severity: 'SEVERITY', explore_affected: 'WHO IS AFFECTED', explore_what: 'WHAT HAPPENED',
    explore_notify_label: '▸ STAY UPDATED', explore_notify_desc: 'New threats are added regularly. Bookmark this page and check back often.',
    stix_label: '▸ THREAT INTELLIGENCE BUNDLE', stix_title: 'STRUCTURED THREAT DATA',
    stix_subtitle: 'The same threat data security experts share — but explained in plain English.',
    stix_what: 'WHAT IS THIS?',
    stix_what_text: 'When security experts discover an attack, they create a structured summary — who did it, what tools they used, what was targeted, and what fingerprints were left. We show you that same data, but explained simply.',
    stix_attacker: 'WHO ATTACKED', stix_tools: 'TOOLS USED', stix_targets: 'WHO WAS TARGETED',
    stix_iocs: 'DIGITAL FINGERPRINTS FOUND', stix_techniques: 'HOW THEY DID IT',
    stix_timeline: 'WHEN IT HAPPENED', stix_download: 'DOWNLOAD RAW DATA ▸', stix_back: 'BACK TO ANALYSIS',
  },
  hi: {
    nav_analyze: 'विश्लेषण', nav_learn: 'सीखें', nav_about: 'परिचय',
    nav_quiz: 'प्रश्नोत्तरी', nav_subtitle: 'साइबर इंटेलिजेंस',
    nav_logout: 'लॉग आउट', nav_logout_desc: 'शुरुआत पर वापस जाएं',
    nav_cve: 'कमज़ोरी खोज', nav_ioc: 'IOC खोज', nav_explore: 'खतरे देखें',
    ob_init: '▸ सिस्टम शुरू हो रहा है',
    ob_step1_label: '▸ चरण 01 — भाषा चुनें',
    ob_step1_title: 'हम आपको क्या बुलाएं?',
    ob_step1_desc: 'आपका अनुभव आपकी प्रोफ़ाइल के अनुसार व्यक्तिगत बनाया जाएगा।',
    ob_step1_placeholder: 'अपना नाम दर्ज करें...',
    ob_step2_label: '▸ चरण 02 — पहचान',
    ob_step2_title: 'स्वागत है', ob_step2_desc: 'अपनी पृष्ठभूमि चुनें ताकि AI आपके लिए सटीक व्याख्या कर सके।',
    ob_step3_label: '▸ चरण 03 — प्रोफ़ाइल सेटअप',
    ob_step3_title: 'अपनी भाषा चुनें', ob_step3_desc: 'अपने पूरे अनुभव के लिए भाषा चुनें।',
    ob_continue: 'आगे बढ़ें ▸', ob_initialize: 'सिस्टम शुरू करें ▸',
    bg_student: 'छात्र', bg_student_desc: 'तकनीक और साइबर सुरक्षा सीख रहे हैं',
    bg_it: 'IT पेशेवर', bg_it_desc: 'IT में काम करते हैं लेकिन सुरक्षा में नहीं',
    bg_manager: 'मैनेजर / एग्जीक्यूटिव', bg_manager_desc: 'टीम का नेतृत्व करते हैं',
    bg_developer: 'डेवलपर', bg_developer_desc: 'कोड लिखते हैं और सॉफ्टवेयर बनाते हैं',
    bg_general: 'आम जनता', bg_general_desc: 'तकनीक से नहीं हैं — बस जानकारी रखना चाहते हैं',
    bg_security: 'सुरक्षा विश्लेषक', bg_security_desc: 'साइबर सुरक्षा या SOC में काम करते हैं',
    home_ready: 'सिस्टम तैयार — प्रोफ़ाइल लोड हो गई', home_welcome: 'वापस स्वागत है',
    home_calibrated: 'के लिए सेट किया गया', home_level: 'स्तर',
    home_label: '▸ खतरा विश्लेषण डीकोडर',
    home_title1: 'कोई भी साइबर हमला।', home_title2: 'सरल हिंदी में।',
    home_subtitle: 'URL या लेख का टेक्स्ट पेस्ट करें। AI इसे आसान भाषा में समझाएगा।',
    home_tab_url: 'URL पेस्ट करें', home_tab_text: 'टेक्स्ट पेस्ट करें',
    home_url_label: '▸ लेख का URL दर्ज करें',
    home_url_desc: 'कोई भी साइबर न्यूज़ URL पेस्ट करें — हम उसे खुद लाकर विश्लेषण करेंगे।',
    home_url_placeholder: 'https://thehackernews.com/...',
    home_url_works: 'इन साइटों से काम करता है: The Hacker News, Bleeping Computer',
    home_fetch_btn: 'लाओ और डीकोड करो ▸', home_fetching: 'लाया जा रहा है...',
    home_text_label: '▸ लेख का टेक्स्ट पेस्ट करें',
    home_text_placeholder: 'यहां साइबर सुरक्षा लेख का टेक्स्ट पेस्ट करें...',
    home_decode_btn: 'खतरा डीकोड करें ▸', home_chars: 'अक्षर लोड हो गए',
    home_awaiting: 'इनपुट का इंतज़ार है...',
    home_examples: '▸ उदाहरण आज़माएं',
    home_fetch_success: 'लेख मिल गया — विश्लेषण लोड हो रहा है...',
    home_fetch_tip: 'सुझाव: कुछ वेबसाइटें एक्सेस ब्लॉक करती हैं। टेक्स्ट पेस्ट करें टैब आज़माएं।',
    home_feat_url: 'URL या टेक्स्ट', home_feat_url_desc: 'सीधे लिंक या लेख का टेक्स्ट पेस्ट करें।',
    home_feat_timeline: 'हमले की समयरेखा', home_feat_timeline_desc: 'हमला कैसे हुआ — चरण दर चरण।',
    home_feat_ioc: 'IOC + CVE + ATT&CK', home_feat_ioc_desc: 'हर तकनीकी शब्द सरल भाषा में।',
    home_feat_personal: 'व्यक्तिगत', home_feat_personal_desc: 'आपकी पृष्ठभूमि के अनुसार व्याख्या।',
    home_example_wannacry: 'WannaCry रैनसमवेयर', home_example_heartbleed: 'Heartbleed बग', home_example_solarwinds: 'SolarWinds हमला',
    exp_back: 'नया विश्लेषण', exp_error_title: '▸ सिस्टम त्रुटि', exp_return: 'वापस जाएं',
    exp_complete: '▸ खतरा विश्लेषण पूर्ण', exp_summary_label: 'सरल सारांश',
    exp_overview: '▸ घटना का सारांश', exp_attacker: 'हमलावर', exp_victim: 'पीड़ित',
    exp_analogy: '▸ वास्तविक जीवन का उदाहरण', exp_timeline: '▸ हमले की समयरेखा',
    exp_intel: '▸ इंटेलिजेंस विवरण',
    exp_ioc_title: 'IOC — समझौते के संकेत', exp_ioc_what: 'IOC क्या है?',
    exp_ioc_simple: 'हैकरों द्वारा छोड़े गए डिजिटल निशान — जैसे संदिग्ध वेबसाइटें, फ़ाइल नाम, या IP पते।',
    exp_cve_title: 'CVE — सॉफ्टवेयर की कमज़ोरी', exp_cve_what: 'CVE क्या है?',
    exp_cve_simple: 'सॉफ्टवेयर की ज्ञात कमज़ोरियों की एक क्रमांकित सूची।',
    exp_attck_title: 'MITRE ATT&CK तकनीकें', exp_attck_what: 'MITRE ATT&CK क्या है?',
    exp_attck_simple: 'हैकर के हर ज्ञात कदम की एक डिक्शनरी — T-नंबरों में कोड की गई।',
    exp_found: 'मिला', exp_none: 'नहीं मिला', exp_identified: 'पहचाना गया', exp_tactics: 'तकनीकें',
    exp_jargon: '▸ तकनीकी शब्द समझाए गए', exp_risk: '▸ खतरे में कौन है', exp_safe: '▸ सुरक्षित कैसे रहें',
    exp_quiz_btn: '▸ अपनी समझ परखें', exp_quiz_desc: 'इस लेख पर आधारित 5 सवालों की प्रश्नोत्तरी लें',
    exp_stix_btn: '▸ थ्रेट इंटेलिजेंस बंडल देखें', exp_stix_desc: 'संरचित खतरे का डेटा सरल प्रारूप में',
    quiz_label: '▸ ज्ञान परीक्षण', quiz_title: 'अपनी समझ परखें',
    quiz_generating: 'सवाल तैयार हो रहे हैं...', quiz_question: 'सवाल', quiz_of: 'में से',
    quiz_correct: 'सही', quiz_wrong: 'गलत', quiz_explanation: 'स्पष्टीकरण',
    quiz_next: 'अगला सवाल ▸', quiz_finish: 'परिणाम देखें ▸', quiz_results: '▸ प्रश्नोत्तरी पूर्ण',
    quiz_score: 'आपका स्कोर', quiz_excellent: 'शानदार! आपने इस खतरे को अच्छी तरह समझा।',
    quiz_good: 'अच्छा प्रयास! आपने ज़्यादातर मुख्य बातें समझीं।',
    quiz_keep: 'सीखते रहें! विश्लेषण फिर से पढ़ें।',
    quiz_retry: 'फिर से कोशिश करें ▸', quiz_back: 'विश्लेषण पर वापस जाएं',
    quiz_error: 'प्रश्न नहीं बन सके। कृपया दोबारा कोशिश करें।',
    loading_title: 'खतरे का विश्लेषण हो रहा है', loading_desc: 'AI डीकोड कर रहा है...',
    learn_label: '▸ ज्ञान का भंडार', learn_title: 'साइबर शब्दकोश',
    learn_subtitle: 'जटिल साइबर शब्दों को ऐसे समझाया जैसे कोई दोस्त समझाए।',
    learn_analogy: 'इस तरह सोचें', learn_example: 'असली कहानी', learn_format: 'प्रारूप',
    learn_cve: 'CVE', learn_cve_full: 'ज्ञात कमजोरियां और उजागरण',
    learn_cve_simple: 'हर सॉफ्टवेयर में खामियां होती हैं। जब कोई खामी हैकर के काम की हो, तो उसे एक आधिकारिक ID नंबर मिलता है — इसी को CVE कहते हैं।',
    learn_cve_analogy: 'सोचिए किसी ने पता लगाया कि सभी Model X कारों का ताला हेयरपिन से खुलता है। सरकार इसे रजिस्टर करती है: सुरक्षा समस्या CVE-2021-44228। CVE बिल्कुल ऐसे काम करता है।',
    learn_cve_example: 'CVE-2021-44228 (Log4Shell) — एक Java टूल में खामी थी जिससे एक संदेश से ही सर्वर हैक हो जाता था। 3 अरब डिवाइस खतरे में थे।',
    learn_cve_format: 'CVE - साल - नंबर',
    learn_ioc: 'IOC', learn_ioc_full: 'समझौते के संकेत',
    learn_ioc_simple: 'जब हैकर किसी सिस्टम में घुसता है तो निशान छोड़ता है — बिल्कुल चोर की तरह। इन डिजिटल निशानों को IOC कहते हैं।',
    learn_ioc_analogy: 'घर आने पर फर्श पर कीचड़ के निशान, टूटी कुंडी, और हटा हुआ लैपटॉप देखते हैं। चोर को नहीं देखा, पर ये निशान बताते हैं कि कोई था — ये सब IOC हैं।',
    learn_ioc_example: 'SolarWinds हमले में SUNBURST फाइल IOC बन गई। दुनिया भर की सुरक्षा टीमें अपने सिस्टम में वह फाइल खोजने लगीं।',
    learn_ioc_format: 'IP पते, URL, फाइल हैश, डोमेन नाम, ईमेल पते',
    learn_mitre: 'MITRE ATT&CK', learn_mitre_full: 'विरोधी रणनीति और तकनीकें',
    learn_mitre_simple: 'हैकर पैटर्न का पालन करते हैं। MITRE ने हजारों हमलों का अध्ययन किया और हर पैटर्न को T1566 जैसा कोड दिया।',
    learn_mitre_analogy: 'शतरंज में उस्ताद एक चाल देखकर तुरंत पहचान लेता है। सुरक्षा विशेषज्ञ ATT&CK ऐसे इस्तेमाल करते हैं — T1566 देखते ही जान जाते हैं फिशिंग हो रही है।',
    learn_mitre_example: 'T1566 = नकली ईमेल। T1486 = फाइलें लॉक करना। WannaCry हमले में विशेषज्ञों ने ATT&CK कोड से जानकारी साझा की।',
    learn_mitre_format: 'T + 4 अंक (जैसे T1566)',
    learn_ransomware: 'Ransomware', learn_ransomware_full: 'फिरौती + सॉफ्टवेयर',
    learn_ransomware_simple: 'एक वायरस जो सभी फाइलें लॉक करके पैसे मांगता है।',
    learn_ransomware_analogy: 'दफ्तर आए और सभी कैबिनेट नए तालों से बंद हैं — नोट है: पैसे दो तो चाबी देंगे। यही रैनसमवेयर है।',
    learn_ransomware_example: '2017 में WannaCry ने UK अस्पतालों को पंगु बनाया। एक Windows अपडेट न लगाने से सर्जरी रद्द हुई।',
    learn_ransomware_format: 'ईमेल अटैचमेंट या बिना पैच किए सॉफ्टवेयर से फैलता है',
    learn_phishing: 'Phishing', learn_phishing_full: 'जानकारी के लिए मछली पकड़ना',
    learn_phishing_simple: 'नकली संदेश जो पासवर्ड या डिटेल्स देने पर मजबूर करता है।',
    learn_phishing_analogy: 'WhatsApp पर बैंक का नकली संदेश — क्लिक किया, डिटेल्स डाली, हैकर के पास पासवर्ड गया।',
    learn_phishing_example: '2020 में Twitter को फिशिंग से हैक किया। IT सपोर्ट बनकर कर्मचारियों से लॉगिन लिया। Obama और Musk के अकाउंट से स्कैम ट्वीट हुए।',
    learn_phishing_format: 'ईमेल, SMS, वॉयस कॉल, नकली वेबसाइटें',
    learn_zeroday: 'Zero-Day', learn_zeroday_full: 'ठीक करने के लिए शून्य दिन',
    learn_zeroday_simple: 'सॉफ्टवेयर में ऐसी खामी जिसकी कंपनी को खबर नहीं — इसलिए कोई सुधार नहीं।',
    learn_zeroday_analogy: 'आपके फ्लैट का ताला क्रेडिट कार्ड से खुलता है — मकान मालिक को नहीं पता। चोर पहले खोज लेता है। सब खतरे में हैं।',
    learn_zeroday_example: '2010 में Stuxnet ने Zero-Day से ईरान के परमाणु संयंत्र नष्ट किए। ईरान को महीनों पता नहीं चला।',
    learn_zeroday_format: '0day — सबसे खतरनाक प्रकार की कमजोरी',
    about_label: '▸ परिचय', about_title: 'HACKDECODED क्या है?',
    about_problem_title: 'हमने जो समस्या देखी',
    about_problem_desc: 'साइबर सुरक्षा की खबरें विशेषज्ञों के लिए लिखी जाती हैं। जब अस्पताल हैक होते हैं, लेख में लिखा होता है CVE और T1566 जैसे शब्द — जो ज़्यादातर लोगों को समझ नहीं आते।',
    about_solution_title: 'हमने क्या बनाया',
    about_solution_desc: 'HackDecoded एक AI अनुवादक है। कोई भी साइबर लेख पेस्ट करें — हम बताते हैं क्या हुआ, किसने किया, कैसे किया, आपको क्या करना चाहिए। आपकी भाषा में।',
    about_who_title: 'यह किसके लिए है',
    about_who_desc: 'हर वह व्यक्ति जो कंप्यूटर साइंस की डिग्री के बिना साइबर सुरक्षा समझना चाहता है।',
    about_how_title: 'यह कैसे काम करता है',
    about_how_desc: 'भाषा और पृष्ठभूमि बताएं। खतरे का लेख पेस्ट करें। AI सब कुछ आपकी भाषा में समझाता है।',
    about_features_title: 'आप यहां क्या कर सकते हैं',
    about_features_desc: 'खतरे के लेख डीकोड करें। CVE नंबर खोजें। ताज़ा खतरे देखें। क्विज़ दें। साइबर शब्द सीखें।',
    about_disclaimer_title: 'ज़रूरी बात',
    about_disclaimer_desc: 'HackDecoded सीखने के लिए है। गंभीर सुरक्षा निर्णयों के लिए पेशेवरों से सलाह लें।',
    cve_page_label: '▸ कमज़ोरी डेटाबेस', cve_page_title: 'कमज़ोरी खोज',
    cve_page_subtitle: 'कोई भी CVE नंबर टाइप करें और सरल हिंदी में जानकारी पाएं।',
    cve_what_label: '▸ CVE नंबर क्या होता है?',
    cve_what_text: 'CVE को पुलिस केस नंबर की तरह सोचें। जब कोई खामी हैकर के काम की हो, तो उसे एक अनोखा नंबर मिलता है।',
    cve_format_label: '▸ नंबर कैसे पढ़ें',
    cve_input_label: '▸ CVE नंबर दर्ज करें',
    cve_search_button: 'खोजें ▸',
    cve_search_error: 'CVE नहीं मिला। कृपया प्रारूप जांचें।',
    cve_search_error_title: '▸ नहीं मिला',
    cve_published: 'प्रकाशित', cve_severity: 'गंभीरता', cve_cvss_score: 'खतरे का स्कोर',
    cve_description: '▸ यह खामी क्या है?', cve_cvss_vector: '▸ तकनीकी विवरण',
    cve_vector_explain_label: '▸ इसका सरल मतलब क्या है?',
    cve_references: '▸ आधिकारिक स्रोत',
    cve_tip: 'आपको क्या करना चाहिए?',
    cve_tip_text: 'स्कोर 0-10। 9-10 (Critical) = तुरंत काम करें। 7-8.9 (High) = जल्दी ठीक करें। 4-6.9 (Medium) = जल्द ठीक करें। 0-3.9 (Low) = सुविधानुसार।',
    cve_try_example: '▸ उदाहरण देखें', cve_ai_label: '▸ सरल व्याख्या', cve_ai_loading: 'AI तकनीकी विवरण पढ़ रहा है...',
    ioc_page_label: '▸ IOC इंटेलिजेंस', ioc_page_title: 'IOC खोज',
    ioc_page_subtitle: 'कोई भी संदिग्ध IP, URL, डोमेन, या फाइल हैश खोजें।',
    ioc_what_label: '▸ IOC क्या है?',
    ioc_what_text: 'IOC डिजिटल अपराधियों के लिए वांटेड पोस्टर की तरह है। अगर सुरक्षा शोधकर्ताओं ने इसे किसी हमले में देखा है, तो यह IOC बन जाता है।',
    ioc_input_label: '▸ संदिग्ध संकेतक दर्ज करें',
    ioc_placeholder: 'IP पता, URL, डोमेन, या फाइल हैश दर्ज करें...',
    ioc_search_button: 'जांचें ▸', ioc_found: 'दुर्भावनापूर्ण के रूप में चिह्नित',
    ioc_not_found: 'हमारे डेटाबेस में नहीं',
    ioc_not_found_desc: 'यह हमारे डेटाबेस में नहीं है। इसका मतलब सुरक्षित नहीं।',
    ioc_type: 'प्रकार', ioc_risk: 'जोखिम स्तर', ioc_context: 'संदर्भ', ioc_action: 'अनुशंसित कार्रवाई',
    explore_label: '▸ लाइव थ्रेट इंटेलिजेंस', explore_title: 'खतरे देखें',
    explore_subtitle: 'सरल भाषा में समझाए गए नवीनतम साइबर खतरे।',
    explore_new_badge: 'नया खतरा', explore_learn_more: 'पूरा विश्लेषण पढ़ें ▸',
    explore_loading: 'नवीनतम खतरे लोड हो रहे हैं...',
    explore_severity: 'गंभीरता', explore_affected: 'कौन प्रभावित है', explore_what: 'क्या हुआ',
    explore_notify_label: '▸ अपडेट रहें', explore_notify_desc: 'नए खतरे नियमित रूप से जोड़े जाते हैं।',
    stix_label: '▸ थ्रेट इंटेलिजेंस बंडल', stix_title: 'संरचित खतरे का डेटा',
    stix_subtitle: 'सुरक्षा विशेषज्ञ जो डेटा साझा करते हैं — सरल हिंदी में।',
    stix_what: 'यह क्या है?',
    stix_what_text: 'जब विशेषज्ञ कोई हमला खोजते हैं, एक संरचित सारांश बनाते हैं। हम वही डेटा सरल भाषा में दिखाते हैं।',
    stix_attacker: 'किसने हमला किया', stix_tools: 'इस्तेमाल किए उपकरण', stix_targets: 'कौन निशाना बना',
    stix_iocs: 'डिजिटल निशान', stix_techniques: 'कैसे किया', stix_timeline: 'कब हुआ',
    stix_download: 'रॉ डेटा डाउनलोड करें ▸', stix_back: 'विश्लेषण पर वापस जाएं',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const getSavedLang = () => {
    const saved = localStorage.getItem('userProfile')
    if (saved) {
      try { return JSON.parse(saved).language || 'en' }
      catch { return 'en' }
    }
    return 'en'
  }
  const [language, setLanguage] = useState(getSavedLang)
  const t = (key) => translations[language]?.[key] || translations['en']?.[key] || key
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}